# Generated by Django 4.2 on 2023-04-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0007_breed_alter_dog_age_alter_dog_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
