# Generated by Django 4.2 on 2023-04-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0009_alter_breed_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=40),
        ),
    ]
